### PR TITLE
j2534: fix RxStatus value in CAN MSG_START_INDICATION

### PR DESCRIPTION
**Pull request by ConnorRigby**
Signed-off-by: Connor Rigby <connorr@hey.com>

### CODE REVIEW

**Comment by dschultzca** [comment]
Are you able to attach a log of the CAN msg start indication just to document it?

**Comment by dschultzca** [comment]
This may have to be further broken out to deal with msg start and TX echo separately.  
Do you have another J2534 library that handles them differently for comparison?

**Comment by ConnorRigby** [comment]
@dschultzca unfortunately i don't know of any other J2534 that is open source so i can't check. My only point of comparison is the Tactrix DLL which behaves in the way that i've changed here. I can grab a log, but i'm not exactly sure what i should be capturing

**Comment by dschultzca** [comment]
A log of the Tractrix DLL showing this value would be great,  I don't think I have one, but I haven't checked for the CAN protocol, only ISO15765 that's why we may need to split the response per protocol.

**Comment by ConnorRigby** [comment]
[with-libj2534.xlsx](https://github.com/dschultzca/j2534/files/9825815/with-libj2534.xlsx)
[with-tactrix.xlsx](https://github.com/dschultzca/j2534/files/9825816/with-tactrix.xlsx)
Here is a pair of logs, i'm not sure if this is exactly what you're looking for - i don't think these are logging as low-level as you want.. 

the one titled `with-libj2534` is an exchange with this particular library on Linux through a tactrix cable with this patch provided. I've been using it as my primary development platform for the last couple weeks.

the log titled `with-tactrix` is the windows DLL.

I didn't look at the protocol of how the device communicates over USB at all if i'm being honest, i just quickly spotted the difference between the two functions and changed it here and the library worked fine using my existing code foro Windows.

**Pull request merged**
